apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: typesense/typesense:26.0
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          args:
            - '--data-dir'
            - '/data'
            - '--api-key=$(API_KEY)'
            - '--enable-cors'
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-key
                  key: api-key
          volumeMounts:
            - mountPath: /data
              name: typesense-data
          ports:
            - containerPort: 8108
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8108
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8108
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8108
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: typesense-data
          persistentVolumeClaim:
            claimName: typesense-data
