apiVersion: batch/v1
kind: CronJob
metadata:
  name: main-etl
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etl
              image: us-central1-docker.pkg.dev/curious-ocean-424202-i9/main-etl-tracky/main-etl-tracky:latest
              command: [ "python", "main.py" ]
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "1000m"
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: password
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: host
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: port
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: database-credentials
                      key: database
          restartPolicy: OnFailure
