apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-web
  template:
    metadata:
      labels:
        app: search-web
    spec:
      containers:
        - name: search-web
          image: us-central1-docker.pkg.dev/curious-ocean-424202-i9/frontend-tracky/frontend-tracky:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3


